name: Build Selenium Image
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image Tag'
        required: true
        default: 'latest'
      base_image:
        description: 'Hub Image'
        required: true
        default: 'deserializeme/gcicudahub:latest'

jobs:
  build-selenium:
    runs-on: self-hosted
    steps:
      - name: clear cache
        run: |
          docker system prune -a --force
        shell: bash

      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            deserializeme/gcicudaselenium
          tags: |
            "${{github.event.inputs.tag}}"
          
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.cuda-selenium
          build-args: |
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
